//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NOTLAR
    {
        public int NOTID { get; set; }
        public Nullable<int> NOTOGRID { get; set; }
        public Nullable<int> NOTDERSID { get; set; }
        public Nullable<int> SINAV1 { get; set; }
        public Nullable<int> SINAV2 { get; set; }
        public Nullable<int> SINAV3 { get; set; }
        public Nullable<int> ORTALAMA { get; set; }
    
        public virtual TBL_DERSLER TBL_DERSLER { get; set; }
        public virtual TBL_OGRENCILER TBL_OGRENCILER { get; set; }
    }
}
